#Recruitment Toy Model
rec_toy_model <- function(
                      PFTs = c("early", "late"),
                      PFT_prptn = c(0.1,0.9),
                      years = 15,
                      n_PFTs = 2,
                      dbh_0 = c(5,5),#starting dbh of the adult cohorts (early and late) (cm)
                      frac_NPP2GPP = 0.3,#the ratio of GPP to NPP
                      frac_NPP2growth = 0.5,#the fraction of NPP that is used for growth
                      precip = bci_precip_1998,#precipitation data from bci in 2013 or 1998; can also put in 1998- an el Nino Year. Just change "2013" to "1998"
                      pct_light_seedling_layer = 0.02,#the percent light at the seedling layer (%top of canopy) 
                      seedbank_0 = 22750, #the initial mass of carbon in the seedbank (g C)
                      seedpool_0 = 12000, #the initial mass of carbon in the seedling pool (g C)
                      litter_0 = 100000, #the initial mass of carbon in the reproductive litterpool (g C)
                      N_0 = 650, #the initial number of seedlings 
                      R_0 = 0, #the initial number of recruits
                      avg_solar_flux_wet = 347.2,
                      avg_solar_flux_dry = 462.96,
                      dry_season_length = 120,#number of days in the dry season
                      soil_moist.x = bci_sm_1998_Lutz_9){ 
#all input units are in g of carbon


  #naming vector input
  names(PFT_prptn) <- PFTs
  names(dbh_0) <- PFTs
  
  
  output <- list()
  j <- 1
  #part 1. Solar insolation to amount of carbon allocated to reproduction per month
  
  #calculating abiotic variables from abiotic parameter values
  wet_season_length <- 365 - dry_season_length
  avg_rad_30_min_wet <- avg_solar_flux_wet * (60*30) #Joules / 30 min interval
  avg_rad_30_min_dry <- avg_solar_flux_dry * (60*30)
  rad_wet <- rep(c(rep(avg_rad_30_min_wet,24),rep(0,24)),(wet_season_length))
  rad_dry <- rep(c(rep(avg_rad_30_min_dry,24),rep(0,24)),(dry_season_length))
  rad_year <- append(rad_dry,rad_wet)#the time series of solar insolation per 30 min time step
  rad <- rep(rad_year, years)
  
  
#CREATING THE TIME SERIES
  day_series <- c()
  for(i in 1:(years*365)){
    day.in <- rep(i, 48)
    day_series <- append(day_series, day.in)
  }
  
  day_series <- rep(day_series, years)
  
  month_series <- rep(c(rep(1, 31*48), rep(2, 28*48), rep(3, 31*48), rep(4, 30*48), rep(5, 31*48), rep(6, 30*48), rep(7, 31*48), rep(8, 31*48), rep(9, 30*48), rep(10, 31*48), rep(11, 30*48), rep(12, 31*48)), years)
  
  year_series <- c()
  for(i in 1:years){
    year.in <- rep(i, 365*48)
    year_series <- append(year_series, year.in)
  }

  #END CREATING THE TIME SERIES
  
  for(PFT in c("early", "late")){
    
    #initializing biotic state variables
    
    cmc_ind <- c() #mass of carbon (g) per individual in the adult cohort
    co_dbh_ind <- c() #dbh of adult cohort
    co_LAI_ind <- c() #LAI of adult cohort
    N_co <- c() #number of individuals in the adult cohort
    c4repro <- c() #the running sum of carbon for reproduction generated by the cohort each 30 min interval
    PFT.x <- c()
    
    #initial conditions
    co_dbh_ind[1] <- dbh_0[PFT] * 10
    cmc_ind[1] <- Chave.AGB(co_dbh_ind[1]/10) * 1.2 * 1000 * 0.4
    co_LAI_ind[1] <- dbh2LAI(dbh = co_dbh_ind[1])
    N_co[1] <- total_area * LAI_cohort / co_LAI_ind[1]
    c4repro[1] <- 0
    PFT.x[1] <- PFT
    
    for(i in 1:((years*17520)-1)){#the number of 30 min timesteps in the model run
 
   
      PFT.x[i+1] <- PFT
        
      cmc_ind[i+1] <- cmc_ind[i] + (co_LAI_ind[i] * rad[i] * epsilon * frac_NPP2GPP * frac_NPP2growth * (1 - efrac(N = N_co[i], co_dbh_ind = co_dbh_ind[i], PFT = PFT.x[i])))
      
      co_dbh_ind[i+1] <- C2dbh(cmc_ind[i+1])
      
      co_LAI_ind[i+1] <- dbh2LAI(co_dbh_ind[i+1])
      
      N_co[i+1] <- total_area * PFT_prptn[PFT] / co_LAI_ind[i+1]
      
      c4repro[i+1] <- (N_co[i] * co_LAI_ind[i] * rad[i] * epsilon * frac_NPP2GPP * efrac(N = N_co[i], co_dbh_ind = co_dbh_ind[i], PFT = PFT.x[i]))
    
      
      print(c(i/(17520), PFT))
    }
    
    
    output[[j]] <- data.frame(day = day_series, 
               year = year_series, 
               month = month_series, 
               PFT.x = PFT.x, 
               cmc_ind = cmc_ind, 
               co_dbh_ind = co_dbh_ind, 
               co_LAI_ind = co_LAI_ind, 
               N_co = N_co, 
               c4repro = c4repro)
    j <- j+1
    
  }
   
names(output) <- PFTs
  
  #### Creating month and day variables for the 30 min time step data so it can be summarized and/or integrated on daily and monthly time steps. #This is a bridge between the 30 min time steps and the daily time steps of the second part of the model. 

   
  #part 2. daily carbon for reproduction to number of recruits into the 1 cm size class
  
  for(PFT in c("early", "late")){
    
    c4_repro_day <- output[[PFT]] %>%
      select(day, c4repro) %>%
      group_by(day) %>%
      summarise(c4_repro_day = sum(c4repro))
    
    c4_repro_day <- c4_repro_day$c4_repro_day
    
    for(dPFT in c("DI", "DT")){
      
    j <- j+1
    
    water_def <- rep(def_func(soil_moist = soil_moist.x,thresh = thresh[dPFT],window = 18*7), years)
    
    l <- pct_light_seedling_layer
    
    l_seedling_dry <- avg_solar_flux_dry/0.327 * l
    l_seedling_wet <- avg_solar_flux_wet/0.327 * l
    
    seedling_light <- rep(c(rep(l_seedling_dry, dry_season_length), rep(l_seedling_wet, wet_season_length)), years)
    
    pct_sl <- (seedling_light * 8.48656E-04 + 0.001975)*100
    
    precip.mod <- data.frame(day = rep(precip$day, years), rain_mm = rep(precip$rain_mm, years))
    
    
    seedbank <- c()
    seedpool <- c()
    litter <- c()
    N <- c()
    R <- c()
    month <- c()
    day <- c()
    frac_emerging <- c()
    H20_mort_rate <- c()
    dPFT.x <- c()
    PFT.x <- c()
    
    
    seedbank[1] <- seedbank_0
    seedpool[1] <- seedpool_0
    litter[1] <- litter_0
    N[1] <- N_0
    R[1] <- R_0
    month[1] <- 0
    day[1] <- 0
    frac_emerging[1] <- 0.0 
    H20_mort_rate[1] <- 0.0
    dPFT.x[1] <- dPFT
    PFT.x[1] <- PFT
    
    for(i in 1:((years*365)-1)){
      
      dPFT.x[i+1] <- dPFT
      
      PFT.x[i+1] <- PFT.x
      
      day[i+1] <- i
      
      month[i+1] <- as.numeric(strsplit(as.character(as.Date(i, origin = "2000-01-01")), "-")[[1]][2])
      
      frac_emerging[i+1] <- (frac_emerg_func(rain = (ifelse(test= i > 7, yes = sum(precip.mod$rain_mm[(i-6):i]), no = 7 * precip.mod$rain_mm[i]))))
      
      seedbank[i+1] <- seedbank[i] - (decay_rate/365 * seedbank[i]) - (frac_emerg_func(rain = (ifelse(test= i > 7, yes = sum(precip.mod$rain_mm[(i-6):i]), no = 7 * precip.mod$rain_mm[i]))) * seedbank[i]) + (seed_frac * c4_repro_day[i])
      
      seedpool[i+1] <- seedpool[i] + ((frac_emerg_func(rain = (ifelse(test= i > 7, yes = sum(precip.mod$rain_mm[(i-6):i]), no = 7 * precip.mod$rain_mm[i])))) *seedbank[i]) - ((light_mort(light = pct_sl[i], seedlings_C = seedpool[i], PFT = PFT, N_smp = 20)) * seedpool[i]) - (H20_mort(deficit_days = water_def[i], PFT = dPFT)*seedpool[i]) - (seedpool[i]*background_seedling_mort/365) - (frac_rec(light = pct_sl[i], t_window = c(5,8), PFT = PFT, N_smp = 50, p1e.x = 0.718, p2e.x = 0.0043, p1l.x = 0.2211, p2l.x = 0.0145, g_param = c(1.07,1.0), seedlings_C = seedpool[i]) * seedpool[i])
      
      N[i+1] <- N[i] + (frac_rec(light = pct_sl[i], t_window = c(5,8), PFT = PFT, N_smp = 50, p1e.x = 0.718, p2e.x = 0.0043, p1l.x = 0.2211, p2l.x = 0.0145, g_param = c(1.07,1.0), seedlings_C = seedpool[i]) * seedpool[i])/(Z0*0.4)
      
      R[i+1] <- (frac_rec(light = pct_sl[i], t_window = c(5,8), PFT = PFT, N_smp = 50, p1e.x = 0.718, p2e.x = 0.0043, p1l.x = 0.2211, p2l.x = 0.0145, g_param = c(1.07,1.0), seedlings_C = seedpool[i]) * seedpool[i]) / (Z0*0.4)
      
      litter[i+1] <- litter[i] + ((1-seed_frac) * c4_repro_day[i]) + (decay_rate/365 * seedbank[i]) + (light_mort(light = pct_sl[i], seedlings_C = seedpool[i], PFT = PFT, N_smp = 20) * seedpool[i]) + (seedpool[i] * background_seedling_mort/365) + H20_mort(deficit_days = water_def[i], PFT = dPFT)*seedpool[i]
      
      H20_mort_rate[i+1] <- H20_mort(deficit_days = water_def[i], PFT = dPFT)
      
     
      
    }
    
    output[[j]] <- data.frame(dPFT.x = dPFT.x,
                              PFT.x = PFT.x,
                              day = day,
                              month = month,
                              c4_repro_day = c4_repro_day,
                              seedbank = seedbank, 
                              frac_emerging = frac_emerging, 
                              H20_mort_rate = H20_mort_rate, 
                              seedpool = seedpool, 
                              litter = litter, 
                              R = R, 
                              N = N)  
    j <- j+1
    
    
    print(c("part2", PFT, dPFT))
    
    }
    
  
}
  
  return(output)
}


undebug(rec_toy_model)
rec_toy_model()





